name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest pytest-cov

    - name: Run unit tests with coverage
      run: |
        coverage run -m unittest discover
        coverage report
        coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml

    - name: Lint code with Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_PYTHON_PYLINT: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
